services:
  nginx:
    image: nginx:${NGINX_TAG}
    container_name: gateway
    restart: always
    ports:
      - "33021:33021"  # gogs
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/
    networks:
      - workspace-net

networks:
  workspace-net:
    external: true   # <--- Tells Compose to use the network created in Step 1