services:
  nginx:
    image: nginx:${NGINX_TAG}
    container_name: gateway
    restart: always
    ports:
      - "30080:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/
    networks:
      - workplace-net

networks:
  workplace-net:
    external: true   # <--- Tells Compose to use the network created in Step 1