services:
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_TAG}
    container_name: vaultwarden
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://vaultwarden.localhost
    volumes:
      - ./vw-data/:/data/
    networks:
      - workplace-net

networks:
  workplace-net:
    external: true