services:
  nginx:
    image: nginx:${NGINX_TAG}
    container_name: app-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs:/etc/nginx/ssl:ro
      - ./html/maintenance.html:/var/www/html/maintenance.html
    networks:
      - workplace-net

networks:
  workplace-net:
    external: true